# Generated by Django 3.1.4 on 2021-07-07 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make',
            name='name',
            field=models.CharField(help_text='Ingrese un fabricante de autos (ej. Audi)', max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'nombre fabricante debe ser mas grande que 1 caracter')], verbose_name='Fabricante'),
        ),
    ]
