# Generated by Django 3.1.4 on 2021-07-08 20:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='name of the cat (min 3 characters)', max_length=100, validators=[django.core.validators.MinLengthValidator(3, 'Cat name should be at least 3 characters')], verbose_name='Cat name')),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Weight (kg)')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.breed')),
            ],
        ),
    ]
